source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'HanekeSwift', '0.10.1'

target 'SwiftUtilities_Example' do
  pod 'SwiftUtilities', :path => '../'
end

target 'SwiftUtilities_Tests' do
  pod 'SwiftUtilities', :path => '../'

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
